set -g mouse on

# set -g default-terminal "tmux-256color"
# set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"
set -g default-terminal "xterm-256color"

set -g prefix2 M-a
bind M-a send-prefix

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Windows Splitting
unbind '"'
unbind %

bind - split-window -v -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind -r x kill-pane

# Set the Status bar to the top
#set-option -g status-position top

# Tmux sensible configurations.
# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 50

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

# Plugin Manager
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'wfxr/tmux-power'

set -g @tmux_power_theme '#0296d1'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
