unbind r
bind r source-file ~/.tmux.conf
set -g mouse on

# set -g default-terminal "tmux-256color"
# set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"
set -g default-terminal "xterm-256color"

set -g prefix2 M-a
bind M-a send-prefix

# vim-like pane switching
bind -r ^ last-window
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

# B for back a window, N for next window. P still works
bind b previous-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Display Popup bindings
unbind n
bind n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'
unbind s
bind s display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
unbind t
bind t display-popup \
  -d "#{pane_current_path}" \
  -w 75% \
  -h 75% \
  -E "bash"


# Windows Splitting
unbind '"'
unbind '%'

bind - split-window -v -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind -r x kill-pane

# Set the Status bar to the top
set-option -g status-position top

# Tmux sensible configurations.
# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 50

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

# Plugin Manager
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'catppuccin/tmux'

# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "custom"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_left_separator "#[fg=#{@thm_overlay_2},bg=default]#[fg=#{@thm_crust},bg=#{@thm_overlay_2}]"
set -g @catppuccin_window_middle_separator " "
set -g @catppuccin_window_right_separator "#[fg=#{@thm_surface_0},bg=default]"
set -g @catppuccin_window_current_left_separator "#[fg=#{@thm_mauve},bg=default]#[fg=#{@thm_crust},bg=#{@thm_mauve}]"
set -g @catppuccin_window_current_middle_separator " "
set -g @catppuccin_window_current_right_separator "#[fg=#{@thm_surface_1},bg=default]"

run ~/.tmux/plugins/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_date_time}"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
